### ISSUE TITLE
Toggle eye irritation configuration

### ISSUE THREAD

**Issue by antonkc** [tubauva/ONI-Mods#1]
Greetings,

I love the CO2 storing part. Without it I fill like it is a useless item. But I can't come to terms with the fact that it also removes eye irritation. I believe it makes it overpowered en comparison to the exosuite.

I just want to ask if it is not a simple change, as in removing (based on configuration) the EffectInmunities added in
[OxygenMaskEyeProtection/OxygenMaskPatches.cs](https://github.com/tubauva/ONI-Mods/blob/b59cdc2c72c0bff4fb336810073a6fd897b3cf69/OxygenMaskEyeProtection/OxygenMaskPatches.cs).

Thanks for the mod. Best regards.

**Comment by tubauva** [comment]
Thank you for the issue! (this is my first)
After a bit of testing it seems that it's not possible to remove the effect immunities while still keeping the airtightsuit tag which controls CO2 collection. I can send you the code I wrote when testing if you'd like! Otherwise I will close this issue.
Best regards.
